ansible_connection: network_cli
ansible_network_os: cisco.ios.ios
ansible_network_cli_ssh_type: paramiko
ansible_command_timeout: 120
ansible_timeout: 60
ansible_port: 22
snmp_group_name: NETOPS
snmp_user: snmpadmin
snmp_auth_algo: sha
snmp_priv_algo: aes 256
snmp_view: READONLY
snmp_acl: SNMP-ACL
snmp_contact: B S Dada Kahalandar
nms_hosts:
  - 10.10.40.100
  - 10.10.40.101
logging_hosts:
  - 10.10.30.50
  - 10.10.30.51
snmp_allowed_networks:
  - 10.10.40.0 0.0.0.255
# --- NTP Configuration ---
# Your internal NTP Servers (AD Controllers or Dedicated NTP)
ntp_servers:
  - 192.168.29.1
# Timezone Settings (IST = GMT +5:30)
timezone_name: "IST"
timezone_offset_hours: 5
timezone_offset_minutes: 30

# Security Timers (Seconds)
site_auth_reauth_timer: 1000      # How often to re-check auth
site_dot1x_tx_period: 9           # Transmit period
site_dot1x_supp_timeout: 15       # Supplicant timeout
