---
- name: IOS | Apply logging configuration
  ios_config:
    src: "{{ lookup('template', '../templates/logging.j2') }}"
  when:
    - logging_enabled | default(true)
  tags:
    - logging
    - logging_apply
