#Test Working
---
- name: Deploy login banner to Cisco IOS
  hosts: Test-IOS-XE-ISRV
  gather_facts: no
  
  vars:
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios
  
  roles:
    - role: common_ios/banner
      vars:
        banner_file: banner.j2
        commit: true
