---
- name: IOS | SNMP BACK-OUT
  hosts: platforms_cisco-ios
  gather_facts: no

  tasks:
    - name: Back-out SNMP configuration
      import_role:
        name: ios_common
        tasks_from: snmp/backout.yml
