---
- name: IOS | SNMP APPLY
  hosts: platforms_cisco-ios
  gather_facts: no

  tasks:
    - name: Apply SNMP configuration
      import_role:
        name: ios_common
        tasks_from: snmp/apply.yml
