---
ansible_connection: network_cli
ansible_network_os: cisco.ios.ios
ansible_ssh_transport: paramiko
ansible_command_timeout: 120
ansible_timeout: 60
ansible_port: 22
snmp_location: "Hyderabad"
source_interface: E0/0
